name: melpazoid

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: Set up Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          sudo apt-get install -y emacs
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid

      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: (typst-watch :fetcher github :repo "pasunboneleve/typst-watch")
          EXIST_OK: false
        run: make -C ~/melpazoid
